// ==============================
// MENU LOADER + CONTROLES
// ==============================
(function(){function getMenuCandidates(){const path=window.location.pathname;const depth=Math.max(path.split('/').filter(Boolean).length-1,0);const relativeRoot=depth>0?'../'.repeat(depth):'./';const version='delta-prompts-20260722-menu-v3';return[`${new URL('menu.html',window.location.href).href}?v=${version}`,`${relativeRoot}menu.html?v=${version}`,`/delta-prompts/menu.html?v=${version}`]}async function fetchMenu(){const urls=[...new Set(getMenuCandidates())];let lastError;for(const url of urls){try{const res=await fetch(url,{cache:'reload'});if(res.ok)return res.text();lastError=new Error(`Falha ao carregar menu: ${res.status}`)}catch(err){lastError=err}}throw lastError||new Error('Falha ao carregar menu')}fetchMenu().then(html=>{const container=document.getElementById('menu');if(!container)return;container.innerHTML=html;attachMenuControls()}).catch(err=>{console.error(err)});window.attachMenuControls=function(){const menuEl=document.getElementById('menu'),sidebar=menuEl&&menuEl.querySelector('.sidebar'),toggle=menuEl&&menuEl.querySelector('.menu-toggle');if(!menuEl||!sidebar||!toggle)return;function setOpen(open){sidebar.classList.toggle('active',open);toggle.setAttribute('aria-expanded',String(open));document.documentElement.classList.toggle('menu-open',open)}toggle.addEventListener('click',e=>{e.stopPropagation();setOpen(!sidebar.classList.contains('active'))});menuEl.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setOpen(false)));document.addEventListener('click',ev=>{if(sidebar.classList.contains('active')&&!sidebar.contains(ev.target)&&!toggle.contains(ev.target))setOpen(false)});document.addEventListener('keydown',ev=>{if(ev.key==='Escape')setOpen(false)});menuEl.querySelectorAll('.menu-section').forEach(section=>{const title=section.querySelector('.menu-title'),links=section.querySelector('.menu-links');if(!title||!links)return;title.addEventListener('click',()=>{menuEl.querySelectorAll('.menu-links').forEach(m=>{if(m!==links)m.classList.remove('active')});links.classList.toggle('active')})})}})();

// PADRAO VISUAL DAS CATEGORIAS
(function(){function enhanceCategoryPage(){const hasPromptCards=document.querySelector('.prompt-text, pre.prompt-text, #lista, #lista-prompts');const hasCategoryHeading=document.querySelector('main > h1');if(hasPromptCards&&hasCategoryHeading)document.body.classList.add('category-page')}document.addEventListener('DOMContentLoaded',enhanceCategoryPage)})();

// PADRONIZA RECURSOS DA PAGINA DE ESTUDO COM A PAGINA DE SAUDE
(function(){function activate(){if(!window.location.pathname.endsWith('/paginas/estudo.html'))return;if(typeof promptsEstudo==='undefined'||typeof ordemCategorias==='undefined'||typeof renderizar!=='function')return;const busca=document.getElementById('busca');const nivelAtual=document.querySelector('.filtro-nivel');if(!busca||!nivelAtual)return;
const wrapper=document.createElement('div');wrapper.className='filtros-container';const categorias=document.createElement('div');categorias.className='filtro-botoes filtro-categoria';categorias.innerHTML='<button type="button" class="ativo" data-categoria="todas">Todas as Categorias</button>'+ordemCategorias.map(cat=>`<button type="button" data-categoria="${cat}">${cat}</button>`).join('');nivelAtual.parentNode.insertBefore(wrapper,nivelAtual);wrapper.appendChild(categorias);wrapper.appendChild(nivelAtual);nivelAtual.classList.add('filtro-botoes');nivelAtual.style.marginBottom='0';const primeiro=nivelAtual.querySelector('button');if(primeiro)primeiro.textContent='Todos os Níveis';
let estadoTexto='';let estadoNivel='todos';let estadoCategoria='todas';function aplicar(){const filtrados=promptsEstudo.filter(p=>{const termo=estadoTexto.toLowerCase();const matchTexto=p.titulo.toLowerCase().includes(termo)||p.prompt.toLowerCase().includes(termo)||p.categoria.toLowerCase().includes(termo);const matchNivel=estadoNivel==='todos'||p.nivel===estadoNivel;const matchCategoria=estadoCategoria==='todas'||p.categoria===estadoCategoria;return matchTexto&&matchNivel&&matchCategoria});renderizar(filtrados)}
window.filtrarPrompts=function(){estadoTexto=busca.value;aplicar()};window.filtrarNivel=function(event,nivel){nivelAtual.querySelectorAll('button').forEach(btn=>btn.classList.remove('ativo'));event.currentTarget.classList.add('ativo');estadoNivel=nivel;aplicar()};categorias.addEventListener('click',event=>{const btn=event.target.closest('button');if(!btn)return;categorias.querySelectorAll('button').forEach(item=>item.classList.remove('ativo'));btn.classList.add('ativo');estadoCategoria=btn.dataset.categoria;aplicar()});
const style=document.createElement('style');style.textContent='.filtros-container{display:flex;flex-direction:column;gap:10px;margin-bottom:20px}.filtro-botoes{display:flex;flex-wrap:wrap;gap:8px}.filtro-botoes button{padding:8px 15px;border:1px solid #ddd;background:#fff;border-radius:20px;cursor:pointer;transition:.3s}.filtro-botoes button:hover{background:#f0f0f0}.filtro-botoes button.ativo{background:#22c55e;color:#fff;border-color:#22c55e}';document.head.appendChild(style)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',activate);else activate()})();

// CARDS EXPLICATIVOS RECOLHÍVEIS GLOBAIS
(function(){function isInfoTitle(text){const t=(text||'').toLowerCase();return t.includes('objetivo')||t.includes('como os prompts')||t.includes('como usar')||t.includes('como funciona')||t.includes('como escolher')||t.includes('estão organizados')||t.includes('estao organizados')}function activate(){document.querySelectorAll('main section.card, main .card').forEach(card=>{if(card.classList.contains('info-collapsible')||card.closest('#lista')||card.closest('#lista-prompts'))return;const heading=card.querySelector(':scope > h2, :scope > h3');if(!heading||!isInfoTitle(heading.textContent))return;const title=heading.innerHTML;const body=document.createElement('div');body.className='info-body';while(card.children.length>1)body.appendChild(card.children[1]);heading.remove();const button=document.createElement('button');button.type='button';button.className='info-toggle';button.setAttribute('aria-expanded','false');button.innerHTML=`<strong>${title}</strong><span class="info-chevron" aria-hidden="true">⌄</span>`;button.addEventListener('click',()=>{const open=card.classList.toggle('info-open');button.setAttribute('aria-expanded',String(open))});card.classList.add('info-collapsible');card.prepend(button);card.appendChild(body)})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',activate);else activate()})();

// GOOGLE ANALYTICS GLOBAL
(function(){const GA_ID='G-1YF2VY4HXW';if(window.gtag)return;const script=document.createElement('script');script.async=true;script.src=`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`;document.head.appendChild(script);window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}window.gtag=gtag;gtag('js',new Date());gtag('config',GA_ID)})();

// CONTADOR PUBLICO DE VISUALIZACOES POR PAGINA
(function(){const API='https://api.counterapi.dev/v1';const NAMESPACE='delta-prompts-jhoncorretor2025';function pageKey(){let path=window.location.pathname.replace(/^\/delta-prompts\/?/,'').replace(/\/$/,'')||'inicio';return path.replace(/\.html$/,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').toLowerCase()||'inicio'}function getCount(data){const values=[data&&data.count,data&&data.value,data&&data.data&&data.data.count,data&&data.data&&data.data.value,data&&data.data];for(const value of values){const n=Number(value);if(Number.isFinite(n))return n}return null}function format(n){return new Intl.NumberFormat('pt-BR').format(n)}function insertBadge(){const main=document.querySelector('main');if(!main||document.getElementById('page-view-counter'))return null;const h1=main.querySelector('h1');if(!h1)return null;const badge=document.createElement('div');badge.id='page-view-counter';badge.className='page-view-counter';badge.setAttribute('aria-live','polite');badge.innerHTML='<span aria-hidden="true">👁️</span> <strong>—</strong> visualizações';h1.insertAdjacentElement('afterend',badge);return badge}async function activate(){const badge=insertBadge();if(!badge)return;const key=pageKey();try{const response=await fetch(`${API}/${encodeURIComponent(NAMESPACE)}/${encodeURIComponent(key)}/up`,{cache:'no-store'});if(!response.ok)throw new Error('contador indisponível');const data=await response.json();const count=getCount(data);if(count===null)throw new Error('resposta inválida');badge.querySelector('strong').textContent=format(count);badge.title='Total público de visualizações desta página'}catch(error){console.warn('Contador de visualizações:',error);badge.remove()}}const style=document.createElement('style');style.textContent='.page-view-counter{display:inline-flex;align-items:center;gap:5px;margin:6px 0 14px;padding:7px 11px;border:1px solid #e5e7eb;border-radius:999px;background:#fff;color:#667085;font-size:13px;line-height:1;box-shadow:0 2px 8px rgba(15,23,42,.04)}.page-view-counter strong{color:#4f46e5;font-size:14px}@media(max-width:600px){.page-view-counter{margin-top:4px}}';document.head.appendChild(style);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',activate);else activate()})();

// FAVORITOS GLOBAIS
(function(){const STORAGE_KEY='deltaFavoritos';window.getFavoritos=function(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch(e){return[]}};window.saveFavoritos=function(list){localStorage.setItem(STORAGE_KEY,JSON.stringify(Array.isArray(list)?list:[]))};window.isFavorito=function(id){return getFavoritos().some(f=>f.id===id)};window.toggleFavorito=function(item){const list=getFavoritos(),i=list.findIndex(f=>f.id===item.id);if(i<0)list.unshift({...item,createdAt:Date.now()});else list.splice(i,1);saveFavoritos(list);return i<0};window.updateFavButtonUI=function(button){if(!button.dataset.id)return;button.classList.toggle('favorito',isFavorito(button.dataset.id));button.innerText=isFavorito(button.dataset.id)?'❤️':'🤍'};window.initFavButtons=function(root=document){root.querySelectorAll('.fav-btn').forEach(updateFavButtonUI)};document.addEventListener('click',e=>{const btn=e.target.closest&&e.target.closest('.fav-btn');if(!btn)return;toggleFavorito({id:btn.dataset.id,titulo:btn.dataset.titulo||'',texto:btn.dataset.texto||'',categoria:btn.dataset.categoria||''});updateFavButtonUI(btn)});document.addEventListener('DOMContentLoaded',()=>initFavButtons())})();